### ISSUE TITLE
Console error report

### ISSUE THREAD

**Issue by Aebestach** [yagiziskirik/Kerbal-Telemetry#1]
![error](https://user-images.githubusercontent.com/64588584/108669327-c5503e00-7517-11eb-8549-bb2ef8389b5b.png)

Hello, yagiziskirik.
In the introduction of the README, I one by one to operate.
But when I opened the webpage, the console reported the error as shown in the above picture. What is the reason?

**Comment by dyzbx** [comment]
![chart](https://user-images.githubusercontent.com/64588584/108733628-a5496a80-7569-11eb-9bec-a127aabcd476.gif)
Digital data does not move, but the graphs will change in the atmosphere. What is the reason?

**Comment by dyzbx** [comment]
![Kerbal Telemetry - Imgur](https://user-images.githubusercontent.com/64588584/108734102-12f59680-756a-11eb-875f-41ff4d231829.png)
As shown in this picture.The rocket is in flight and not activated.

**Comment by yagiziskirik** [comment]
Hello, @dyzbx 

Sorry for the delay, I didn't receive the issue e-mails. Normally without initiating the flight, the system doesn't become active. Apparently, you already did that. If the warning you mentioned in the javascript console showed up only a few times, it is completely fine. Would you mind to send the screenshot of Python console and check if the "Kerbal Telemetry\static\data.json" file exists? Because chart data is separate from the rest. Also, you can attach the file, I really would like to solve the problem. Thank you for letting me know.

**Comment by yagiziskirik** [comment]
Also if you updated it from the previous version, you can clear the cache of the website.
You can do it on Google Chrome by executing ```Ctrl + Shift + R```

**Comment by dyzbx** [comment]
@yagiziskirik 
Thank you for your reply.
I just tried again (to clear up the browser cache) and found the same problem.
I checked the "data.json" file and found that the data in it has changed. The "Kerbal X" has become the rocket I launched.
I also saved the Console output, which is the file "Console output.txt"
[Console output.txt](https://github.com/yagiziskirik/Kerbal-Telemetry/files/6026771/Console.output.txt)

**Comment by Aebestach** [comment]
You can also post a topic on KSP Forum to let more people see your mod.😊

**Comment by yagiziskirik** [comment]
I found ```UnicodeDecodeError: 'gbk' codec can't decode byte 0xab in position 325: illegal multibyte sequence``` on your Python console. It is most probably caused by an error in the *data.json* file, which created by the KSP side of the program. I suspect about string values which sometimes includes quotation marks in them. I suppose I couldn't make the program failsafe enough. And since this is the only ticket I received about any program on Github, I couldn't ask for the right files. I am deeply sorry about stealing some of your time to fix it. Would you mind if you can send the *data.json* file as well? I can fix the problem on the KSP side and release a new version thanks to you.

By the way, ![Version 2.1.0](https://img.shields.io/badge/version-2.1.0-blue) will also include some of the disabled buttons to become active again. Also thank you for the KSP Forum tip, I will definitely do that today and include your name on the KSP Forum release.

**Comment by Aebestach** [comment]
![zh-cn](https://user-images.githubusercontent.com/64588584/108836699-1fcac680-760c-11eb-93df-5ef87cb0a4f0.jpg)

I used it.

![stock](https://user-images.githubusercontent.com/64588584/108836747-2eb17900-760c-11eb-8a7f-38cd6b9924b2.jpg)

The original.


I have compared your data.json file with mine and found that there are some Chinese characters in mine.
Could it be an error caused by Chinese characters?

**Comment by Aebestach** [comment]
[data.txt](https://github.com/yagiziskirik/Kerbal-Telemetry/files/6028575/data.txt)
JSON file cannot be uploaded directly, I changed the suffix to .TXT.

**Comment by Aebestach** [comment]
`{
	"altitude": 2082.04090854083,
	"distanceTraveled": 1845.01826801728,
	"externalTemperature": 21.8607670471618,
	"GForce": 2.10053293389575,
	"canComm": "TRUE",
	"situation": "Flying Low",
	"timeToPe": 298.756545324157,
	"lat": -0.0971878868966601,
	"lon": -74.5612092539402,
	"verticalSpeed": 195.541486010248,
	"missionTime": 21.8599999999964,
	"speed": 194.436706542969,
	"name": "Z-MAP卫星发射套装",
	"atmDensity": 0.872740953070768,
	"currentStage": 6,
	"deltaV": 2973.05072784424,
	"timeToAp": 20.2579088161604,
	"orbitSpeed": 258.764152093525,
	"orbitIncl": 0.0977658244894513,
	"orbitEcc": 0.995119383319716,
	"ApA": 4052.73874914553,
	"PeA": -598522.319066639,
	"horizSpeed": 6.07028580130172,
	"partCount": 82,
	"mass": 17.4300180766732,
	"acceleration": 10.916797836663,
	"convFlux": -1628.6848270193,
	"radFlux": -18.7681627782213,
	"intFlux": 29790.7279778828,
	"planetName": "Kerbin",
	"yaw": 270.282043457031,
	"pitch": 88.3402404785156,
	"roll": -90.1180725097656,
	"coolTemp": 36.5577114107738,
	"coolSkinTemp": 36.557898991074,
	"coolSkinName": "EAS-4支架连接器",
	"hotTemp": 161.979711747469,
	"hotSkinTemp": 84.8788658502055,
	"hotSkinName": "RT-10“巨锤”固体燃料助推器",
	"critTemp": 36.5572071054675,
	"critSkinTemp": 36.5581799946961,
	"critSkinName": "OX-STAT太阳能电池板",
	"targetName": "NON",
	"distance": 0,
	"targetSpeed": 0
}
`

**Comment by Aebestach** [comment]
There is no way to upload json files directly on github.

**Comment by Aebestach** [comment]
I just switched to the English version of the game and tried it, and found that the English version can run normally.

**Comment by yagiziskirik** [comment]
I tried the program with your data which gave the exact same error. I am trying to give the program Chinese character support right now, it is a lot of encoding decoding process. I am working on it, and try to make a universal solution. Thank you again.

**Comment by Aebestach** [comment]
😀
Thank you for bringing this mod.
I especially look forward to the emergence of this feature.(Orbit animation when orbitting the Kerbin.)

**Comment by yagiziskirik** [comment]
It is been a really tough few hours trying to fix the problem. Unfortunately, I couldn't be able to manage to encode Chinese characters on the website. I created the code to encode but since the *data.json* file is too long, it becomes more time consuming and doubles the CPU power needed. I couldn't find a suitable solution for this problem and I am deeply sorry about it. The only solution that I could find is to play in English.

And also I thank you for creating this issue ticket. It really makes me happy that people are interested in this project. You can see an insider view of the orbit animation. It is my way to thank you back. (Sorry for the low resolution)
<br>
![world](https://user-images.githubusercontent.com/33431578/108855045-36175900-75f1-11eb-916d-01ad5838efc4.gif)

**Comment by yagiziskirik** [comment]
Hello again @Aebestach,

I fixed the Chinese character errors and translated the interface to Chinese as well (as an option of course, and it is probably not that great). I will be releasing the new version in a couple of days. I am glad to say that this issue will be fixed soon.

**Comment by Aebestach** [comment]
Awesome, looking forward to the release of the new version.
