### ISSUE TITLE
Orbit animation

### ISSUE THREAD

**Issue by jxpsert** [yagiziskirik/Kerbal-Telemetry#4]
Hey there!
First of all- great mod. It is awesome.

Now, in another issue and on the readme, screenshots show an orbit animation around the planet.
Is this simply not yet released, or is it not working on my end? I'm using the latest release, and running it using Python 3.9.2.

The launch sites also seem to not show up every time, they seem to appear and disappear at random reloads.

**Comment by yagiziskirik** [comment]
Hello @jxpsert,

In version [v2.1.0](https://github.com/yagiziskirik/Kerbal-Telemetry/releases/tag/v2.1.0), orbit animations work. Let me remind you that it will only work when vessel has been launched from the web interface. I am working on orbit animations on manual launches as well. Also make sure that you have the latest update and if it is still not working, you can clear the cache of your browser. You can follow [this](https://superuser.com/questions/278948/clear-cache-for-specific-domain-name-in-chrome) link to specifically clear the cache of a specific website for Chrome (in this case, Kerbal Telemetry). Other than that, I know that on any Mac ```⌘⇧R``` will also do the exact same thing. (Note that I use ```ctrl + shift + r``` on Chrome as well.)

Launch site issue is caused by the timeout that I gave it is not working properly. I will fix it and update it on the next v2.1.1 update.

Also I found out that arrow keys on the index page also not working. I will going to fix them too.

Also thank you for your support. You guys help me a lot to develop this mod.
