### ISSUE TITLE
Program not start

### ISSUE THREAD

**Issue by megamoster** [yagiziskirik/Kerbal-Telemetry#6]
![image](https://user-images.githubusercontent.com/52428534/116738817-9bc20000-a9fb-11eb-94eb-9826653ea212.png)

Error

OR THIS 

![image](https://user-images.githubusercontent.com/52428534/116738945-c8761780-a9fb-11eb-99bd-e8fb4449c230.png)

If it starts it does not start

![Без імені](https://user-images.githubusercontent.com/52428534/116744050-771d5680-aa02-11eb-93a9-66ef0b21a32f.png)

**Comment by yagiziskirik** [comment]
Hello @megamoster,

Since I don't know Russian, I couldn't quite understand the issue. As far as I can guess from the `ERR_CONNECTION_REFUSED` error message, there is a problem with the Telemetry Server script. Would you mind if I ask you to send me the terminal console output from the cmd window? In this way, I can understand the issue and help you better.

Thank you for reporting this issue. You guys help me to make this mod better.

**Comment by megamoster** [comment]
I understand that the mistake was on my side. In my computer
**_.py files didn't run_** at all by I solved this problem like this:

1. Opened the command line and wrote "**start python**"
2. And dragged the "**TelemetryServer.py**" file to the command line
3. I pressed "**Enter**" and everything started as it should.

**Thank you for wanting to help me**

**Comment by yagiziskirik** [comment]
I am glad to try to help you. If you encounter any additional problems, you can open a new issue as well. I hope you will like the Kerbal Telemetry. Have a wonderful day.

**Comment by megamoster** [comment]
Ok, thanks.
