### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by Covenant2021** [yagiziskirik/Kerbal-Telemetry#7]
Will there be a tutorial on how to install? Anyway, what operating system are you running?
Because it doesn't work for me.

**Comment by yagiziskirik** [comment]
Hello @Covenant2021,

Actually, I created a [Setup](https://github.com/yagiziskirik/Kerbal-Telemetry#setup) section under the Readme file. I use Windows 10, macOS Big Sur and Ubuntu 20.04 LTS, all the systems running the latest version of the KSP. The setup process is pretty much the same under all the systems since KSP is natively supported under these systems.

You can follow the setup process and let me know if you are stuck at some point. I will try to help if you encounter any problems or issues.

**Comment by Covenant2021** [comment]
Thank you very much! Well then you switch to Windows 10. opps
